# Generated by Django 5.1.3 on 2024-11-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_reservationmodel_reservation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='date_reserved',
            field=models.DateField(help_text='Date reserved'),
        ),
    ]
