# Generated by Django 5.1.3 on 2024-11-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_reservationmodel_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='Cancelled reservation status'),
        ),
    ]
